export const RANKS = [
  { key: 'unranked',    label: 'アンランク',     tier: 'unranked',   value: 0,  short: 'UR'  },
  { key: 'iron1',       label: 'アイアン 1',     tier: 'iron',       value: 1,  short: 'I1'  },
  { key: 'iron2',       label: 'アイアン 2',     tier: 'iron',       value: 2,  short: 'I2'  },
  { key: 'iron3',       label: 'アイアン 3',     tier: 'iron',       value: 3,  short: 'I3'  },
  { key: 'bronze1',     label: 'ブロンズ 1',     tier: 'bronze',     value: 4,  short: 'B1'  },
  { key: 'bronze2',     label: 'ブロンズ 2',     tier: 'bronze',     value: 5,  short: 'B2'  },
  { key: 'bronze3',     label: 'ブロンズ 3',     tier: 'bronze',     value: 6,  short: 'B3'  },
  { key: 'silver1',     label: 'シルバー 1',     tier: 'silver',     value: 7,  short: 'S1'  },
  { key: 'silver2',     label: 'シルバー 2',     tier: 'silver',     value: 8,  short: 'S2'  },
  { key: 'silver3',     label: 'シルバー 3',     tier: 'silver',     value: 9,  short: 'S3'  },
  { key: 'gold1',       label: 'ゴールド 1',     tier: 'gold',       value: 10, short: 'G1'  },
  { key: 'gold2',       label: 'ゴールド 2',     tier: 'gold',       value: 11, short: 'G2'  },
  { key: 'gold3',       label: 'ゴールド 3',     tier: 'gold',       value: 12, short: 'G3'  },
  { key: 'platinum1',   label: 'プラチナ 1',     tier: 'platinum',   value: 13, short: 'P1'  },
  { key: 'platinum2',   label: 'プラチナ 2',     tier: 'platinum',   value: 14, short: 'P2'  },
  { key: 'platinum3',   label: 'プラチナ 3',     tier: 'platinum',   value: 15, short: 'P3'  },
  { key: 'diamond1',    label: 'ダイヤ 1',       tier: 'diamond',    value: 16, short: 'D1'  },
  { key: 'diamond2',    label: 'ダイヤ 2',       tier: 'diamond',    value: 17, short: 'D2'  },
  { key: 'diamond3',    label: 'ダイヤ 3',       tier: 'diamond',    value: 18, short: 'D3'  },
  { key: 'ascendant1',  label: 'アセンダント 1', tier: 'ascendant',  value: 19, short: 'A1'  },
  { key: 'ascendant2',  label: 'アセンダント 2', tier: 'ascendant',  value: 20, short: 'A2'  },
  { key: 'ascendant3',  label: 'アセンダント 3', tier: 'ascendant',  value: 21, short: 'A3'  },
  { key: 'immortal1',   label: 'イモータル 1',   tier: 'immortal',   value: 22, short: 'IM1' },
  { key: 'immortal2',   label: 'イモータル 2',   tier: 'immortal',   value: 23, short: 'IM2' },
  { key: 'immortal3',   label: 'イモータル 3',   tier: 'immortal',   value: 24, short: 'IM3' },
  { key: 'radiant',     label: 'レディアント',   tier: 'radiant',    value: 25, short: 'RAD' },
]

export const RANK_MAP = Object.fromEntries(RANKS.map(r => [r.key, r]))
